### ISSUE TITLE
Merge from external source results in 403

### ISSUE THREAD

**Issue by mcjaeger** [codescoop/osman#10]
For some strange reason, for a special case, there is 403 returned when merging with external source. Assume a user created record:

![image](https://user-images.githubusercontent.com/3418977/54202680-dc372a80-44d0-11e9-92c2-7abcacbfdf9f.png)

then, pick a project:

![image](https://user-images.githubusercontent.com/3418977/54202709-e9ecb000-44d0-11e9-9e41-118151b7342b.png)

in this case pick eclipse/jetty-servlet:

![image](https://user-images.githubusercontent.com/3418977/54202741-fa048f80-44d0-11e9-84fd-5521db5b82d5.png)

and confirm results in a 403:

![image](https://user-images.githubusercontent.com/3418977/54202780-11dc1380-44d1-11e9-8490-39a7e6d7117f.png)

**Comment by sweetca** [comment]
solved
